### ISSUE TITLE
Improve Settings Class

### ISSUE THREAD

**Issue by maxkostinevich** [maxkostinevich/WP-Plugin-Starter-Kit#3]
Related file: /includes/class-plugin-name-settings.php

Class should be refactored. 
Move settings definition to private function to allow apply custom filters and hooks to plugin settings.

Add code samples.

**Comment by Thorworx** [comment]
This starter kit is just about perfect.

However, the one issue that I'm really struggling with is how to implement a "Reset to defaults" button in the settings (global for all options).

I'm sure that this is probably simple - but I'm fairly new to this, and I'm having difficulty finding examples of how to incorporate this into my plugin while using the starter kit (create a function, and call init when clicking a reset button?). 

Is this something you would consider adding for the improved settings class?
.. or could you point me in the right direction for doing this myself with the existing kit?

**Comment by maxkostinevich** [comment]
@Thorworx To achieve this you should define default value for a settings (see plugin_name_textarea_1 in class-plugin-name-settings.php for example). Then you should bind a function to "Reset to defaults" which will loop through $plugin_settings array and update setting value to its default value (or remove the setting if default value isn't set). Hope it helps.

**Comment by Thorworx** [comment]
@maxkostinevich Thanks for your reply.. I appreciate it.
Since the startup kit already sets defaults in `settings_setup_default_values()`, I was hoping to somehow use that - or modify it to remove and reset all settings if called from my reset input button. As I said, I'm new to this (and my php is not the strongest), so I'll keep trying to come up with something. Thanks again for your good work.
